<?php

namespace Walterra\J4p5Bundle\j4p5\jsc;

use Walterra\J4p5Bundle\j4p5\jsc\js_construct;

class js_program extends js_construct {
    static $source;
    function __construct($obj) {
        $this->src= $obj;
        self::$source = $obj;
    }

    function emit($w=0)   {
        $source = $this->src->emit(1);

        $o = "/* Code generated by J4P5, the javascript interpreter for PHP5\n";
        $o.= "     * http://j4p5.sf.net/ copyright(c) 2005 Henri T. <metal_hurlant@users.sourceforge.net>\n";
        $o.= "     */\n\n";
        $o.= $source;
        return $o;
    }
}

?>